export const QueryKeys = {
  CREATE_PURCHASE_SESSION: "CREATE_PURCHASE_SESSION",
  GET_CART: "GET_CART",
  GET_CART_BY_ID: "GET_CART_BY_ID",

  GET_EVENT_DETAILS_BY_ID: "GET_EVENT_DETAILS_BY_ID",
};
